### ISSUE TITLE
Flatpak support for avogadro2

### ISSUE THREAD

**Issue by jakobjakobson13** [OpenChemistry/avogadroapp#97]
Dear developers,

could you provide flatpak support for avogadro2? I also made a rough preliminary sketch of the build manifest.
```yml
app-id: org.OpenChemistry.avogadro2
runtime: org.kde.Platform
runtime-version: "5.9"
sdk: org.kde.Sdk
command: flatpak-demo
finish-args: 
  - --share=ipc
  - --socket=x11
  - --socket=wayland
  - --filesystem=host
  - --device=dri
modules: 
- name: avogadro2
  buildsystem: cmake
  build-options:
    - build 
    - config 1.91.0 
  sources: 
    - type: git
      url: git://github.com/OpenChemistry/openchemistry

```

With that preliminary manifest I get as far as
```bash
...
-- Set runtime path of "/run/build/avogadro/prefix/bin/molequeue" to "/run/build/avogadro/prefix/lib"
[ 15%] Completed 'molequeue'
[ 15%] Built target molequeue
make: *** [Makefile:84: all] Error 2
```

but I don't know how the handle the error.

Regards

**Comment by ghutchis** [comment]
Hi - thanks for the message, but it’s hard to know how to handle the error without more from the `make` run. Can you post the whole log, e.g., to a gist or Pastebin or similar?

Thanks!

**Comment by jakobjakobson18** [comment]
Hi,
can you pass a different location (other than their download link) of eigen, glu, msgpack  to the cmake compilation of avogadro2? I think this is the reason for the error and fixitng could  help a lot.

**Comment by jakobjakobson13** [comment]
The following manifest
 ```
app-id: org.OpenChemistry.avogadro
runtime: org.kde.Platform
runtime-version: '5.14'
sdk: org.kde.Sdk
command: avogadro
finish-args: 
  - --share=ipc
  - --socket=x11
  - --socket=wayland
  - --device=dri
modules:
- name: eigen
  buildsystem: cmake
  builddir: true
  sources:
    - type: archive
      url: https://gitlab.com/libeigen/eigen/-/archive/3.3.7/eigen-3.3.7.tar.gz
      sha256: d56fbad95abf993f8af608484729e3d87ef611dd85b3380a8bad1d5cbc373a57
- name: spglib
  buildsystem: cmake
  builddir: true
  sources:
    - type: archive
      url: https://github.com/atztogo/spglib/archive/v1.15.0.tar.gz
      sha256: 2e217beff6840a22ab2149598eb2f40616b2eeb9e155edab52761d3301412f98
- name: mmtf
  buildsystem: cmake
  builddir: true
  sources:
    - type: archive
      url: https://github.com/rcsb/mmtf-cpp/archive/v1.0.0.tar.gz
      sha256: 881f69c4bb56605fa63fd5ca50842facc4947f686cbf678ad04930674d714f40
- name: glew  # can later be substituted by flathub maintained version
  no-autogen: true
  make-args:
    - GLEW_PREFIX=/app
    - GLEW_DEST=/app
    - LIBDIR=/app/lib
  make-install-args:
    - GLEW_PREFIX=/app
    - GLEW_DEST=/app
    - LIBDIR=/app/lib
  sources:
    - type: archive
      url: https://downloads.sourceforge.net/project/glew/glew/2.1.0/glew-2.1.0.tgz
      sha256: 04de91e7e6763039bc11940095cd9c7f880baba82196a7765f727ac05a993c95
  cleanup:
    - /include
    - /lib/pkgconfig
    - /lib/*.a
- name: libglvnd
  buildsystem: autotools
  builddir: true
  sources:
    - type: archive
      url: https://gitlab.freedesktop.org/glvnd/libglvnd/-/archive/v1.3.1/libglvnd-v1.3.1.tar.gz
      sha256: b26c931ff79feced0d1ac69332797a08427308fa85541282ee9995680c880b24
- name: libmsym
  buildsystem: cmake
  builddir: true
  sources:
    - type: archive      
      url: https://github.com/mcodev31/libmsym/archive/v0.2.3-paper.tar.gz
      sha256: 3741ebe163cf40696570d6b62e4834ca587d43dcac9de713994cc5e2960fb8fd
- name: molequeue
  buildsystem: cmake
  builddir: true
  sources:
    - type: archive
      url: https://github.com/OpenChemistry/molequeue/archive/0.9.0.tar.gz
      sha256: 7dd234742c8d73be95281fedf4ed9d09648ecc351afb5f098cd32f48c3df3bd5
- name: avogadrolib
  buildsystem: cmake
  build-options:
    - build 
    - config 1.93.0 
  sources: 
    - type: archive
      url: https://github.com/OpenChemistry/avogadrolibs/archive/1.93.0.tar.gz
      sha256: 01fea1f3b21c69091c60739616f86123db92f445e4c9ca53f1dec09624aceab4
- name: avogadroapp
  buildsystem: cmake
  build-options:
    - build 
    - config 1.93.0 
  sources: 
    - type: archive
      url: https://github.com/OpenChemistry/avogadroapp/archive/1.93.0.tar.gz
      sha256: 8cf913058aff58fe588531618a680d82401fbfe3f21e4783a44979f4a2dd5586

```

builds all dependencies and starts to build the avogadrolib up to the point where the following error messages are shown:

```
-- The C compiler identification is GNU 9.2.0
-- The CXX compiler identification is GNU 9.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting build type to 'Debug' as none was specified.
-- Performing Test HAVE_GCC_ERROR_RETURN_TYPE
-- Performing Test HAVE_GCC_ERROR_RETURN_TYPE - Success
-- Found Git: /usr/bin/git (found version "2.23.0") 
-- Could not use git to determine source version, using version 1.93.0
-- Found Eigen3: /app/include/eigen3 (Required is at least version "2.91.0") 
-- Could NOT find SPGLIB (missing: SPGLIB_INCLUDE_DIR SPGLIB_LIBRARY) 
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Found MMTF: /app/include  
CMake Warning (dev) at /usr/share/cmake-3.15/Modules/FindOpenGL.cmake:275 (message):
  Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
  available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  FindOpenGL found both a legacy GL library:

    OPENGL_gl_LIBRARY: /usr/lib/x86_64-linux-gnu/libGL.so

  and GLVND libraries for OpenGL and GLX:

    OPENGL_opengl_LIBRARY: /usr/lib/x86_64-linux-gnu/libOpenGL.so
    OPENGL_glx_LIBRARY: /usr/lib/x86_64-linux-gnu/libGLX.so

  OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
  compatibility with CMake 3.10 and below the legacy GL library will be used.
Call Stack (most recent call first):
  avogadro/rendering/CMakeLists.txt:6 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so   
-- Found GLEW: /app/include  
-- Could NOT find PythonInterp (missing: PYTHON_EXECUTABLE) (Required is at least version "2")
Avogadro Generators not found at /run/build/avogadrolib/../avogadrogenerators!
-- Found LIBARCHIVE: /usr/include  
msym include dir /app/lib/cmake/libmsym/../../../include
CMake Warning (dev) at /usr/share/cmake-3.15/Modules/FindOpenGL.cmake:275 (message):
  Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
  available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  FindOpenGL found both a legacy GL library:

    OPENGL_gl_LIBRARY: /usr/lib/x86_64-linux-gnu/libGL.so

  and GLVND libraries for OpenGL and GLX:

    OPENGL_opengl_LIBRARY: /usr/lib/x86_64-linux-gnu/libOpenGL.so
    OPENGL_glx_LIBRARY: /usr/lib/x86_64-linux-gnu/libGLX.so

  OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
  compatibility with CMake 3.10 and below the legacy GL library will be used.
Call Stack (most recent call first):
  avogadro/qtplugins/overlayaxes/CMakeLists.txt:3 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
SPGLIB_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /run/build/avogadrolib/avogadro/core
   used as include directory in directory /run/build/avogadrolib/avogadro/core
   used as include directory in directory /run/build/avogadrolib/avogadro/core
   used as include directory in directory /run/build/avogadrolib/avogadro/core
   used as include directory in directory /run/build/avogadrolib/avogadro/core
   used as include directory in directory /run/build/avogadrolib/avogadro/core
   used as include directory in directory /run/build/avogadrolib/avogadro/core
SPGLIB_LIBRARY (ADVANCED)
    linked by target "AvogadroCore" in directory /run/build/avogadrolib/avogadro/core

-- Configuring incomplete, errors occurred!
See also "/run/build/avogadrolib/CMakeFiles/CMakeOutput.log".
Error: module avogadrolib: Der Kindprozess wurde mit Status 1 beendet
```

How can I fix this?
